name: pop-health-ml
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - jupyter>=1.0.0
  - pytest>=6.2.0
  - pytorch>=1.10.0
  - torchvision>=0.11.0
  - pip
  - pip:
    - xgboost>=1.5.0
    - lightgbm>=3.3.0
    - lifelines>=0.27.0
    - scikit-survival>=0.17.0
    - pycox>=0.2.0
    - tensorflow>=2.7.0
    - keras>=2.7.0
    - econml>=0.13.0
    - causalml>=0.13.0
    - dowhy>=0.8.0
    - stable-baselines3>=1.6.0
    - gym>=0.21.0
    - statsmodels>=0.13.0
    - pingouin>=0.5.0
    - plotly>=5.0.0
    - bokeh>=2.4.0
    - pyarrow>=6.0.0
    - openpyxl>=3.0.0
    - tqdm>=4.62.0
    - joblib>=1.1.0
    - dill>=0.3.0
    - cloudpickle>=2.0.0
    - pyyaml>=6.0
    - configparser>=5.2.0
    - pytest-cov>=3.0.0
    - sphinx>=4.0.0
    - sphinx-rtd-theme>=1.0.0
    - ipykernel>=6.0.0
    - ipywidgets>=7.6.0
    - shap>=0.40.0
    - lime>=0.2.0
    - eli5>=0.11.0
    - optuna>=2.10.0
    - hyperopt>=0.2.0
    - scikit-optimize>=0.9.0
    - tslearn>=0.5.0
    - sktime>=0.11.0
    - krippendorff>=0.5.0
    - fleiss-kappa>=1.0.0
    - mlflow>=1.20.0
    - wandb>=0.12.0
    - great-expectations>=0.15.0
    - pandera>=0.11.0

